config/routes.rb
Rails.application.routes.draw do
  resources :widgets
  resources :boxes
  resources :settings
  resources :pages
  resources :users

end

app/models/box.rb
class Box < ActiveRecord::Base
end

app/controllers/boxes_controller.rb
class BoxesController < ApplicationController
  before_action :set_box, only: [:show, :edit, :update, :destroy]

  # GET /boxes
  # GET /boxes.json
  def index
    @boxes = Box.all
  end

  # GET /boxes/1
  # GET /boxes/1.json
  def show
  end

  # GET /boxes/new
  def new
    @box = Box.new
  end

  # GET /boxes/1/edit
  def edit
  end

  # POST /boxes
  # POST /boxes.json
  def create
    @box = Box.new(box_params)

    respond_to do |format|
      if @box.save
        format.html { redirect_to @box, notice: 'Box was successfully created.' }
        format.json { render :show, status: :created, location: @box }
      else
        format.html { render :new }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /boxes/1
  # PATCH/PUT /boxes/1.json
  def update
    respond_to do |format|
      if @box.update(box_params)
        format.html { redirect_to @box, notice: 'Box was successfully updated.' }
        format.json { render :show, status: :ok, location: @box }
      else
        format.html { render :edit }
        format.json { render json: @box.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /boxes/1
  # DELETE /boxes/1.json
  def destroy
    @box.destroy
    respond_to do |format|
      format.html { redirect_to boxes_url, notice: 'Box was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_box
      @box = Box.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def box_params
      params.require(:box).permit(:page_id, :widget_id, :box_width, :box_height)
    end
end

app/helpers/boxes_helper.rb
module BoxesHelper
end

app/views/boxes/_form.html.erb
<%= form_for(@box) do |f| %>
  <% if @box.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@box.errors.count, "error") %> prohibited this box from being saved:</h2>

      <ul>
      <% @box.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :page_id %><br>
    <%= f.number_field :page_id %>
  </div>
  <div class="field">
    <%= f.label :widget_id %><br>
    <%= f.number_field :widget_id %>
  </div>
  <div class="field">
    <%= f.label :box_width %><br>
    <%= f.number_field :box_width %>
  </div>
  <div class="field">
    <%= f.label :box_height %><br>
    <%= f.number_field :box_height %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/boxes/edit.html.erb
<h1>Editing Box</h1>

<%= render 'form' %>

<%= link_to 'Show', @box %> |
<%= link_to 'Back', boxes_path %>

app/views/boxes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Boxes</h1>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>Widget</th>
      <th>Box width</th>
      <th>Box height</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @boxes.each do |box| %>
      <tr>
        <td><%= box.page_id %></td>
        <td><%= box.widget_id %></td>
        <td><%= box.box_width %></td>
        <td><%= box.box_height %></td>
        <td><%= link_to 'Show', box %></td>
        <td><%= link_to 'Edit', edit_box_path(box) %></td>
        <td><%= link_to 'Destroy', box, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Box', new_box_path %>

app/views/boxes/new.html.erb
<h1>New Box</h1>

<%= render 'form' %>

<%= link_to 'Back', boxes_path %>

app/views/boxes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @box.page_id %>
</p>

<p>
  <strong>Widget:</strong>
  <%= @box.widget_id %>
</p>

<p>
  <strong>Box width:</strong>
  <%= @box.box_width %>
</p>

<p>
  <strong>Box height:</strong>
  <%= @box.box_height %>
</p>

<%= link_to 'Edit', edit_box_path(@box) %> |
<%= link_to 'Back', boxes_path %>